### ISSUE TITLE
Languages folder + relevant readme.txt

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/EDD-Extension-Boilerplate#10]
I think it's a good idea to add a `languages` folder to the root of the plugin. It's referenced from the load `load_textdomain()` method in the main file anyway. It would also be helpful to add a readme.txt file to that directory with either simple instructions for the plugin developer (maybe a bad idea if it doesn't get removed) and for the user (links to relevant WP docs for translation).

Any objections?

**Comment by ghost1227** [comment]
Fixed with 501c0994de5559bdf552d36e2a52b0e6b216edb7
