### ISSUE TITLE
Improvement: Demonstrate sample Activation

### ISSUE THREAD

**Issue by fireproofsocks** [easydigitaldownloads/EDD-Extension-Boilerplate#12]
What might go into the "activation" function?  Can you include some examples?

**Comment by pippinsplugins** [comment]
If your extension needs to create any custom database tables or initial options in the wp_options table, you would place them here.

**Comment by ghost1227** [comment]
Also, you could take a look at the EDD activation function. It does a number of things on first run that should give you a better idea of the possibilities.
