### ISSUE TITLE
PLUGINNAME replace text should really be PLUGIN_NAME

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/EDD-Extension-Boilerplate#15]
https://github.com/easydigitaldownloads/EDD-Extension-Boilerplate/blob/master/plugin-name/plugin-name.php#L30

But there are no instances of PLUGINNAME in any of the files.

All constants use PLUGIN_NAME

https://github.com/easydigitaldownloads/EDD-Extension-Boilerplate/blob/master/plugin-name/plugin-name.php#L95

**Comment by pippinsplugins** [comment]
Ping @ghost1227

**Comment by ghost1227** [comment]
Fixed thanks to @NikV
