### ISSUE TITLE
Revise EDD needed notice with install/activate links

### ISSUE THREAD

**Issue by michael-cannon** [easydigitaldownloads/EDD-Extension-Boilerplate#4]
For https://github.com/easydigitaldownloads/EDD-Extension-Boilerplate/blob/master/plugin-name/includes/class.extension-activation.php#L86, update with similar code from https://github.com/michael-cannon/aihrus-framework/blob/master/aihrus-framework.php#L226.

**Comment by ghost1227** [comment]
Fixed with abe31d72109eb2d94dc04dd0717990b1a314486c
